# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x11knowledge_service\"I\n\x11\x42uildIndexRequest\x12\x0e\n\x06kb_dir\x18\x01 \x01(\t\x12\x11\n\tmodel_dir\x18\x02 \x01(\t\x12\x11\n\tindex_dir\x18\x03 \x01(\t\"N\n\x12\x42uildIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x64ocument_count\x18\x03 \x01(\x05\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"r\n\x0eSearchResponse\x12\x39\n\x07results\x18\x01 \x03(\x0b\x32(.knowledge_service.SearchResponse.Result\x1a%\n\x06Result\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"\x0f\n\rStatusRequest\"0\n\x0eStatusResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\x8e\x02\n\x10KnowledgeService\x12Y\n\nBuildIndex\x12$.knowledge_service.BuildIndexRequest\x1a%.knowledge_service.BuildIndexResponse\x12M\n\x06Search\x12 .knowledge_service.SearchRequest\x1a!.knowledge_service.SearchResponse\x12P\n\tGetStatus\x12 .knowledge_service.StatusRequest\x1a!.knowledge_service.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUILDINDEXREQUEST']._serialized_start=32
  _globals['_BUILDINDEXREQUEST']._serialized_end=105
  _globals['_BUILDINDEXRESPONSE']._serialized_start=107
  _globals['_BUILDINDEXRESPONSE']._serialized_end=185
  _globals['_SEARCHREQUEST']._serialized_start=187
  _globals['_SEARCHREQUEST']._serialized_end=232
  _globals['_SEARCHRESPONSE']._serialized_start=234
  _globals['_SEARCHRESPONSE']._serialized_end=348
  _globals['_SEARCHRESPONSE_RESULT']._serialized_start=311
  _globals['_SEARCHRESPONSE_RESULT']._serialized_end=348
  _globals['_STATUSREQUEST']._serialized_start=350
  _globals['_STATUSREQUEST']._serialized_end=365
  _globals['_STATUSRESPONSE']._serialized_start=367
  _globals['_STATUSRESPONSE']._serialized_end=415
  _globals['_KNOWLEDGESERVICE']._serialized_start=418
  _globals['_KNOWLEDGESERVICE']._serialized_end=688
# @@protoc_insertion_point(module_scope)
